name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: rust-build/rust-build.action@v1
        with:
          project-name: phira-mp-server
          version: ${{ github.event.release.tag_name }}
          build-command: cargo build --release -p phira-mp-server
          targets: linux/amd64,linux/arm64,windows/amd64,darwin/amd64
