name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  release: # 添加release触发器
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }} # 使用矩阵策略
    strategy:
      matrix:
        os: [windows-latest] # 指定windows和linux环境
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release -p phira-mp-server # 构建命令
    - name: Upload release asset # 使用upload-release-asset action
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }} # 获取upload_url
        asset_path: target/release/phira-mp-server.exe # windows平台的asset_path
        asset_name: phira-mp-server-${{ matrix.os }}.exe # windows平台的asset_name
        if-no-files-found: error # 如果没有找到文件则报错
